apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      run: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: docker.io/ukeh11/udagram-reverseproxy:v21
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---          
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy 
  name: reverseproxy
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy